<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPUAVINW0114" name="com.epam.brb.testsModified.PersInfoPagePrevAddrStreetName" tests="3" failures="0" timestamp="27 Sep 2013 10:19:57 GMT" time="28.779" errors="1">
  <testcase name="persInfo081" time="12.386" classname="com.epam.brb.testsModified.PersInfoPagePrevAddrStreetName"/>
  <testcase name="persInfo080" time="4.458" classname="com.epam.brb.testsModified.PersInfoPagePrevAddrStreetName">
    <error type="java.lang.AssertionError" message="the field is not with the entered text expected [ASD123 &#039;-] but found [asd123 &#039;-]">
      <![CDATA[java.lang.AssertionError: the field is not with the entered text expected [ASD123 '-] but found [asd123 '-]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.epam.brb.testsModified.PersInfoPagePrevAddrStreetName.persInfo080(PersInfoPagePrevAddrStreetName.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- persInfo080 -->
  <testcase name="persInfo082" time="11.935" classname="com.epam.brb.testsModified.PersInfoPagePrevAddrStreetName"/>
</testsuite> <!-- com.epam.brb.testsModified.PersInfoPagePrevAddrStreetName -->
